window.equipmentData = [
    // === MAIN BATTLE TANKS ===
    {
        id: 1,
        name: "M1 Abrams",
        type: "Main Battle Tank",
        origin: "United States",
        coords: [39.8283, -98.5795],
        image: "assets/m1_abrams_1765118350420.jpg",
        specs: { speed: "67 km/h", armament: "120mm M256", range: "426 km" },
        inService: 1980,
        users: ["United States", "Australia", "Egypt", "Iraq", "Kuwait", "Saudi Arabia"],
        status: "Active",
        fact: "The M1 Abrams is powered by a 1,500 hp gas turbine engine, giving it exceptional acceleration and allowing it to run on multiple fuel types including jet fuel, diesel, and gasoline.",
        imageCredit: "Photo: Spc. Matthew Marcellus / U.S. Army / Public Domain"
    },
    {
        id: 2,
        name: "Leopard 2A7",
        type: "Main Battle Tank",
        origin: "Germany",
        coords: [51.1657, 10.4515],
        image: "assets/leopard2_17655118389229.jpg",
        specs: { speed: "72 km/h", armament: "120mm L/55", range: "500 km" },
        inService: 2014,
        users: ["Germany", "Hungary", "Qatar"],
        status: "Active",
        fact: "The Leopard 2A7 features modular composite armor that can be quickly reconfigured for different threat environments, making it one of the most adaptable main battle tanks in service.",
        imageCredit: "Photo: Fric.matej / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 3,
        name: "Challenger 2",
        type: "Main Battle Tank",
        origin: "United Kingdom",
        coords: [55.3781, -3.4360],
        image: "assets/challenger2_1765118411349.jpg",
        specs: { speed: "59 km/h", armament: "120mm L30A1", range: "450 km" },
        inService: 1998,
        users: ["United Kingdom", "Oman"],
        status: "Active",
        fact: "Despite being deployed in combat extensively, only one Challenger 2 has been destroyed by enemy fire, showcasing its exceptional armor protection - the best of any NATO tank.",
        imageCredit: "Photo: Graeme Main/MOD / Wikimedia Commons / OGL v1.0"
    },
    {
        id: 4,
        name: "T-90MS",
        type: "Main Battle Tank",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "assets/t90_1765118367473.jpg",
        specs: { speed: "60 km/h", armament: "125mm 2A46M-5", range: "550 km" },
        inService: 2011,
        users: ["Russia", "India", "Algeria", "Iraq"],
        status: "Active",
        fact: "The T-90MS features the Shtora-1 defensive suite, which can detect laser targeting and automatically deploy smoke grenades or jam incoming guided missiles.",
        imageCredit: "Photo: Aleksey Kitaev / Wikimedia Commons / CC BY-SA 3.0"
    },
    {
        id: 5,
        name: "Merkava Mk.4",
        type: "Main Battle Tank",
        origin: "Israel",
        coords: [31.0461, 34.8516],
        image: "assets/merkava4_1765118431134.jpg",
        specs: { speed: "64 km/h", armament: "120mm MG253", range: "500 km" },
        inService: 2004,
        users: ["Israel"],
        status: "Active",
        imageCredit: "Photo: MathKnight and Zachi Evenor / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 6,
        name: "Type 99A",
        type: "Main Battle Tank",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "assets/type99a_tank.jpg",
        specs: { speed: "80 km/h", armament: "125mm ZPT-98", range: "600 km" },
        inService: 2011,
        users: ["China"],
        status: "Active",
        imageCredit: "Photo: Tyg728 / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 7,
        name: "K2 Black Panther",
        type: "Main Battle Tank",
        origin: "South Korea",
        coords: [35.9078, 127.7669],
        image: "assets/k2_black_panther.jpg",
        specs: { speed: "70 km/h", armament: "120mm L/55", range: "450 km" },
        inService: 2014,
        users: ["South Korea", "Poland"],
        status: "Active",
        imageCredit: "Photo: Staff Sgt. Matthew Foster / U.S. National Guard / Public Domain"
    },
    {
        id: 8,
        name: "Pokpung-ho",
        type: "Main Battle Tank",
        origin: "North Korea",
        coords: [39.0392, 125.7625],
        image: "assets/pokpung_ho.jpg",
        specs: { speed: "60 km/h", armament: "125mm smoothbore", range: "300 km" },
        inService: 2002,
        users: ["North Korea"],
        status: "Active",
        imageCredit: "Photo: Stefan Krasowski / Flickr / CC BY 2.0"
    },
    {
        id: 9,
        name: "Zulfiqar-3",
        type: "Main Battle Tank",
        origin: "Iran",
        coords: [32.4279, 53.6880],
        image: "assets/zulfiqar_3.jpg",
        specs: { speed: "70 km/h", armament: "125mm smoothbore", range: "450 km" },
        inService: 2016,
        users: ["Iran"],
        status: "Active",
        imageCredit: "Photo: M-ATF / military.ir / CC BY-SA 3.0"
    },
    {
        id: 10,
        name: "Arjun Mk.2",
        type: "Main Battle Tank",
        origin: "India",
        coords: [20.5937, 78.9629],
        image: "assets/arjun_mk2.jpg",
        specs: { speed: "58 km/h", armament: "120mm rifled gun", range: "450 km" },
        inService: 2014,
        users: ["India"],
        status: "Active",
        imageCredit: "Photo: Anirvan Shukla / Wikimedia Commons / CC BY-SA 3.0"
    },
    {
        id: 11,
        name: "Leclerc",
        type: "Main Battle Tank",
        origin: "France",
        coords: [46.2276, 2.2137],
        image: "assets/leclerc.jpg",
        specs: { speed: "72 km/h", armament: "120mm CN120-26", range: "550 km" },
        inService: 1992,
        users: ["France", "UAE", "Jordan"],
        status: "Active",
        imageCredit: "Photo: Daniel Steger / OpenPhoto.net / CC BY-SA 2.5"
    },
    {
        id: 12,
        name: "Type 10",
        type: "Main Battle Tank",
        origin: "Japan",
        coords: [36.2048, 138.2529],
        image: "assets/type_10.jpg",
        specs: { speed: "70 km/h", armament: "120mm L/44", range: "440 km" },
        inService: 2012,
        users: ["Japan"],
        status: "Active",
        imageCredit: "Photo: TGoto / Wikimedia Commons / Public Domain"
    },

    // === FIGHTER AIRCRAFT ===
    {
        id: 13,
        name: "F-35 Lightning II",
        type: "Fighter Aircraft",
        origin: "United States",
        coords: [38.8814, -77.0365],
        image: "assets/f35.jpg",
        specs: { speed: "Mach 1.6", armament: "AIM-120, GBU-31", range: "2,200 km" },
        inService: 2015,
        users: ["United States", "UK", "Italy", "Netherlands", "Australia", "Norway", "Japan", "Israel", "South Korea"],
        status: "Active",
        imageCredit: "Photo: Noah Wulf / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 14,
        name: "JAS 39 Gripen E",
        type: "Fighter Aircraft",
        origin: "Sweden",
        coords: [60.1282, 18.6435],
        image: "assets/gripen_1765118486549.jpg",
        specs: { speed: "Mach 2", armament: "Meteor, RBS-15", range: "3,200 km" },
        inService: 2019,
        users: ["Sweden", "Brazil", "South Africa", "Thailand", "Czech Republic", "Hungary", "Colombia", "Ukraine"],
        status: "Active",
        imageCredit: "Photo: Milan Nykodym / Wikimedia Commons / CC BY-SA 2.0"
    },
    {
        id: 15,
        name: "F-22 Raptor",
        type: "Fighter Aircraft",
        origin: "United States",
        coords: [33.7490, -84.3880],
        image: "assets/f22_raptor.jpg",
        specs: { speed: "Mach 2.25", armament: "AIM-120, AIM-9", range: "2,960 km" },
        inService: 2005,
        users: ["United States"],
        status: "Active",
        imageCredit: "Photo: Airwolfhound / Wikimedia Commons / CC BY-SA 2.0"
    },
    {
        id: 16,
        name: "Su-57 Felon",
        type: "Fighter Aircraft",
        origin: "Russia",
        coords: [56.3269, 44.0059],
        image: "assets/su57_felon.jpg",
        specs: { speed: "Mach 2", armament: "R-77M, Kh-59MK2", range: "3,500 km" },
        inService: 2020,
        users: ["Russia"],
        status: "Active - Limited Production",
        imageCredit: "Photo: Anna Zvereva / Flickr / CC BY-SA 2.0"
    },
    {
        id: 17,
        name: "IRIAF F-14 Tomcat",
        type: "Fighter Aircraft",
        origin: "Iran",
        coords: [35.6892, 51.3890],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/IRIAF_F-14A_Tomcat.jpg/640px-IRIAF_F-14A_Tomcat.jpg",
        specs: { speed: "Mach 2.34", armament: "AIM-54 Phoenix", range: "2,960 km" },
        inService: 1976,
        users: ["Iran"],
        status: "Active"
    },
    {
        id: 18,
        name: "MiG-29 Fulcrum",
        type: "Fighter Aircraft",
        origin: "Russia",
        coords: [55.7558, 37.6173],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/MiG-29K_at_MAKS-2007_airshow_%28altered%29.jpg/640px-MiG-29K_at_MAKS-2007_airshow_%28altered%29.jpg",
        specs: { speed: "Mach 2.25", armament: "R-73, R-27", range: "1,430 km" },
        inService: 1983,
        users: ["Russia", "India", "North Korea", "Iran", "Poland"],
        status: "Active"
    },
    {
        id: 19,
        name: "J-20 Mighty Dragon",
        type: "Fighter Aircraft",
        origin: "China",
        coords: [30.5728, 104.0668],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/J-20_at_Airshow_China_2016.jpg/640px-J-20_at_Airshow_China_2016.jpg",
        specs: { speed: "Mach 2.0", armament: "PL-15, PL-21", range: "5,500 km" },
        inService: 2017,
        users: ["China"],
        status: "Active"
    },
    {
        id: 20,
        name: "Rafale",
        type: "Fighter Aircraft",
        origin: "France",
        coords: [48.8566, 2.3522],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Rafale_-_RIAT_2009_%283751416421%29.jpg/640px-Rafale_-_RIAT_2009_%283751416421%29.jpg",
        specs: { speed: "Mach 1.8", armament: "MICA, Meteor, SCALP", range: "3,700 km" },
        inService: 2001,
        users: ["France", "Egypt", "Qatar", "India", "Greece"],
        status: "Active"
    },
    {
        id: 21,
        name: "Eurofighter Typhoon",
        type: "Fighter Aircraft",
        origin: "Germany",
        coords: [52.5200, 13.4050],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Eurofighter_Typhoon_MOD_45119541.jpg/640px-Eurofighter_Typhoon_MOD_45119541.jpg",
        specs: { speed: "Mach 2.0", armament: "AMRAAM, ASRAAM, Meteor", range: "3,790 km" },
        inService: 2003,
        users: ["Germany", "UK", "Italy", "Spain", "Saudi Arabia"],
        status: "Active"
    },
    {
        id: 22,
        name: "Qaher-313",
        type: "Fighter Aircraft",
        origin: "Iran",
        coords: [35.6892, 51.3890],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Qaher-313.jpg/640px-Qaher-313.jpg",
        specs: { speed: "Unknown", armament: "Unknown", range: "Unknown" },
        inService: 2017,
        users: ["Iran"],
        status: "Development"
    },

    // === NAVAL VESSELS ===
    {
        id: 23,
        name: "USS Gerald R. Ford",
        type: "Naval Vessel",
        origin: "United States",
        coords: [36.9466, -76.3130],
        image: "assets/uss_ford_carrier.jpg",
        specs: { speed: "56+ km/h", armament: "75+ Aircraft", range: "Unlimited (Nuclear)" },
        inService: 2017,
        users: ["United States Navy"],
        status: "Active",
        imageCredit: "Photo: Mass Communication Specialist 2nd Class Ridge Leoni / U.S. Navy / Public Domain"
    },
    {
        id: 24,
        name: "Type 055 Destroyer",
        type: "Naval Vessel",
        origin: "China",
        coords: [31.2304, 121.4737],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Chinese_Navy_Type_055_destroyer.jpg/640px-Chinese_Navy_Type_055_destroyer.jpg",
        specs: { speed: "55+ km/h", armament: "112 VLS cells", range: "9,300 km" },
        inService: 2020,
        users: ["China"],
        status: "Active"
    },
    {
        id: 25,
        name: "Kirov-class Battlecruiser",
        type: "Naval Vessel",
        origin: "Russia",
        coords: [69.0833, 33.4167],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Kirov-class_battlecruiser.jpg/640px-Kirov-class_battlecruiser.jpg",
        specs: { speed: "59 km/h", armament: "P-700 Granit missiles", range: "Unlimited (Nuclear)" },
        inService: 1980,
        users: ["Russia"],
        status: "Active"
    },
    {
        id: 26,
        name: "Queen Elizabeth-class Carrier",
        type: "Naval Vessel",
        origin: "United Kingdom",
        coords: [50.8036, -1.0644],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/HMS_Queen_Elizabeth_in_New_York_City.jpg/640px-HMS_Queen_Elizabeth_in_New_York_City.jpg",
        specs: { speed: "46 km/h", armament: "40+ F-35B Aircraft", range: "18,500 km" },
        inService: 2017,
        users: ["United Kingdom"],
        status: "Active"
    },
    {
        id: 27,
        name: "Sinpo-class Submarine",
        type: "Naval Vessel",
        origin: "North Korea",
        coords: [40.0096, 127.6651],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Sinpo-class_submarine.jpg/640px-Sinpo-class_submarine.jpg",
        specs: { speed: "Unknown", armament: "Pukguksong SLBM", range: "Unknown" },
        inService: 2014,
        users: ["North Korea"],
        status: "Active"
    },

    // === AIR DEFENSE SYSTEMS ===
    {
        id: 28,
        name: "S-400 Triumf",
        type: "Air Defense System",
        origin: "Russia",
        coords: [55.7558, 37.6173],
        image: "assets/s400_1765118527696.jpg",
        specs: { speed: "Static", armament: "40N6 Missiles", range: "400 km" },
        inService: 2007,
        users: ["Russia", "China", "Turkey", "India", "Belarus"],
        status: "Active",
        imageCredit: "Photo: Vitaly V. Kuzmin / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 29,
        name: "Patriot PAC-3",
        type: "Air Defense System",
        origin: "United States",
        coords: [32.7767, -96.7970],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Patriot_System_2.jpg/640px-Patriot_System_2.jpg",
        specs: { speed: "Static", armament: "MIM-104F", range: "70 km" },
        inService: 1984,
        users: ["United States", "Germany", "Japan", "Saudi Arabia", "Israel"],
        status: "Active"
    },
    {
        id: 30,
        name: "Iron Dome",
        type: "Air Defense System",
        origin: "Israel",
        coords: [32.0853, 34.7818],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flickr_-_Israel_Defense_Forces_-_Iron_Dome_Intercepts_Rockets_from_the_Gaza_Strip.jpg/640px-Flickr_-_Israel_Defense_Forces_-_Iron_Dome_Intercepts_Rockets_from_the_Gaza_Strip.jpg",
        specs: { speed: "Static", armament: "Tamir interceptors", range: "70 km" },
        inService: 2011,
        users: ["Israel", "United States"],
        status: "Active"
    },
    {
        id: 31,
        name: "Bavar-373",
        type: "Air Defense System",
        origin: "Iran",
        coords: [35.6892, 51.3890],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Bavar-373.jpg/640px-Bavar-373.jpg",
        specs: { speed: "Static", armament: "Sayyad-4 missiles", range: "300 km" },
        inService: 2019,
        users: ["Iran"],
        status: "Active"
    },
    {
        id: 32,
        name: "HQ-9",
        type: "Air Defense System",
        origin: "China",
        coords: [39.9042, 116.4074],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chinese_HQ-9_SAM_-_panoramio.jpg/640px-Chinese_HQ-9_SAM_-_panoramio.jpg",
        specs: { speed: "Static", armament: "HQ-9 missiles", range: "200 km" },
        inService: 1997,
        users: ["China", "Pakistan"],
        status: "Active"
    },

    // === ARTILLERY ===
    {
        id: 33,
        name: "CAESAR",
        type: "Artillery",
        origin: "France",
        coords: [48.8566, 2.3522],
        image: "assets/caesar_1765118550941.jpg",
        specs: { speed: "100 km/h", armament: "155mm L/52", range: "42 km" },
        inService: 2008,
        users: ["France", "Denmark", "Czech Republic", "Ukraine", "Indonesia"],
        status: "Active",
        imageCredit: "Photo: Markus Rauchenberger / U.S. Army / Public Domain"
    },
    {
        id: 34,
        name: "M270 MLRS",
        type: "Artillery",
        origin: "United States",
        coords: [38.2527, -85.7585],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/M270_MLRS.jpg/640px-M270_MLRS.jpg",
        specs: { speed: "64 km/h", armament: "227mm rockets", range: "300 km" },
        inService: 1983,
        users: ["United States", "UK", "Germany", "France", "Japan"],
        status: "Active"
    },
    {
        id: 35,
        name: "2S19 Msta",
        type: "Artillery",
        origin: "Russia",
        coords: [56.3269, 44.0059],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/2S19_Msta-S.jpg/640px-2S19_Msta-S.jpg",
        specs: { speed: "60 km/h", armament: "152mm 2A64", range: "29 km" },
        inService: 1989,
        users: ["Russia", "Ukraine", "Belarus"],
        status: "Active"
    },
    {
        id: 36,
        name: "K9 Thunder",
        type: "Artillery",
        origin: "South Korea",
        coords: [37.5665, 126.9780],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/K9_Thunder_self-propelled_howitzer.jpg/640px-K9_Thunder_self-propelled_howitzer.jpg",
        specs: { speed: "67 km/h", armament: "155mm L/52", range: "40 km" },
        inService: 1999,
        users: ["South Korea", "Turkey", "Poland", "India", "Norway"],
        status: "Active"
    },
    {
        id: 37,
        name: "Koksan (M-1978)",
        type: "Artillery",
        origin: "North Korea",
        coords: [39.0392, 125.7625],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/M1978_Koksan.jpg/640px-M1978_Koksan.jpg",
        specs: { speed: "40 km/h", armament: "170mm M-1978", range: "60 km" },
        inService: 1978,
        users: ["North Korea", "Iran"],
        status: "Active"
    },

    // === COMBAT DRONES ===
    {
        id: 38,
        name: "Bayraktar TB2",
        type: "Combat Drone",
        origin: "Turkey",
        coords: [38.9637, 35.2433],
        image: "assets/bayraktar_1765118506987.jpg",
        specs: { speed: "220 km/h", armament: "MAM-L, MAM-C", range: "150 km" },
        inService: 2014,
        users: ["Turkey", "Ukraine", "Azerbaijan", "Libya", "Poland"],
        status: "Active",
        imageCredit: "Photo: Bayhaluk / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 39,
        name: "MQ-9 Reaper",
        type: "Combat Drone",
        origin: "United States",
        coords: [36.5860, -121.8556],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/MQ-9_Reaper_UAV.jpg/640px-MQ-9_Reaper_UAV.jpg",
        specs: { speed: "482 km/h", armament: "Hellfire, GBU-12", range: "1,850 km" },
        inService: 2007,
        users: ["United States", "UK", "France", "Italy"],
        status: "Active"
    },
    {
        id: 40,
        name: "Shahed-136",
        type: "Combat Drone",
        origin: "Iran",
        coords: [35.6892, 51.3890],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Shahed-136.jpg/640px-Shahed-136.jpg",
        specs: { speed: "185 km/h", armament: "40kg warhead", range: "2,000 km" },
        inService: 2021,
        users: ["Iran", "Russia"],
        status: "Active"
    },
    {
        id: 41,
        name: "Wing Loong II",
        type: "Combat Drone",
        origin: "China",
        coords: [39.9042, 116.4074],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Wing_Loong_II.jpg/640px-Wing_Loong_II.jpg",
        specs: { speed: "370 km/h", armament: "BA-7, YZ-212", range: "4,000 km" },
        inService: 2017,
        users: ["China", "UAE", "Saudi Arabia", "Pakistan"],
        status: "Active"
    },

    // === ASSAULT RIFLES ===
    {
        id: 42,
        name: "M4A1 Carbine",
        type: "Assault Rifle",
        origin: "United States",
        coords: [41.4925, -72.8231],
        image: "assets/m4a1_carbine.jpg",
        specs: { speed: "N/A", armament: "5.56x45mm NATO", range: "500 m" },
        inService: 1994,
        users: ["United States", "NATO allies", "80+ countries worldwide"],
        status: "Active",
        imageCredit: "Photo: PEO Soldier / Derivative: MathKnight / Wikimedia Commons / Public Domain"
    },
    {
        id: 43,
        name: "AK-74M",
        type: "Assault Rifle",
        origin: "Russia",
        coords: [56.8431, 60.6454],
        image: "assets/ak74m_rifle.jpg",
        specs: { speed: "N/A", armament: "5.45x39mm", range: "500 m" },
        inService: 1991,
        users: ["Russia", "Belarus", "Kazakhstan", "Former Soviet states"],
        status: "Active",
        imageCredit: "Photo: Vitaly Kuzmin / Wikimedia Commons / CC BY-SA 4.0"
    },
    {
        id: 44,
        name: "QBZ-95",
        type: "Assault Rifle",
        origin: "China",
        coords: [39.9042, 116.4074],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/QBZ-95_automatic_rifle.jpg/640px-QBZ-95_automatic_rifle.jpg",
        specs: { speed: "N/A", armament: "5.8x42mm DBP87", range: "400 m" },
        inService: 1997,
        users: ["China"],
        status: "Active"
    },
    {
        id: 45,
        name: "Type 88 (North Korea)",
        type: "Assault Rifle",
        origin: "North Korea",
        coords: [39.0392, 125.7625],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Type_88-2_rifle.jpg/640px-Type_88-2_rifle.jpg",
        specs: { speed: "N/A", armament: "5.45x39mm", range: "440 m" },
        inService: 1988,
        users: ["North Korea"],
        status: "Active"
    },
    {
        id: 46,
        name: "KH-2002 Khaybar",
        type: "Assault Rifle",
        origin: "Iran",
        coords: [32.4279, 53.6880],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Khaybar_KH-2002.jpg/640px-Khaybar_KH-2002.jpg",
        specs: { speed: "N/A", armament: "5.56x45mm NATO", range: "450 m" },
        inService: 2004,
        users: ["Iran"],
        status: "Active"
    },

    // === ARMOURED PERSONNEL CARRIERS ===
    // Chinese APCs
    {
        id: 47,
        name: "ZBD-04",
        type: "Infantry Fighting Vehicle",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/ZBD-04_IFV_20170902.jpg/640px-ZBD-04_IFV_20170902.jpg",
        specs: { speed: "75 km/h", armament: "30mm cannon", range: "600 km" },
        inService: 2004,
        users: ["China"],
        status: "Active",
        fact: "The ZBD-04 is amphibious and can swim at speeds up to 30 km/h, making it one of the fastest amphibious IFVs in the world."
    },
    {
        id: 48,
        name: "ZBL-09",
        type: "Armoured Personnel Carrier",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/ZBL-09_IFV_at_the_2015_Moscow_Victory_Day_Parade.jpg/640px-ZBL-09_IFV_at_the_2015_Moscow_Victory_Day_Parade.jpg",
        specs: { speed: "100 km/h", armament: "30mm cannon", range: "800 km" },
        inService: 2009,
        users: ["China", "Venezuela"],
        status: "Active",
        fact: "The ZBL-09 is an 8x8 wheeled APC that forms the backbone of China's rapid deployment forces, with over 1,000 units produced."
    },
    {
        id: 49,
        name: "Type 89",
        type: "Infantry Fighting Vehicle",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Type_89_IFV_-_1.jpg/640px-Type_89_IFV_-_1.jpg",
        specs: { speed: "65 km/h", armament: "73mm gun", range: "500 km" },
        inService: 1999,
        users: ["China"],
        status: "Active"
    },

    // Russian APCs
    {
        id: 50,
        name: "BTR-82A",
        type: "Armoured Personnel Carrier",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/BTR-82A_-_TankBiathlon14part1-33.jpg/640px-BTR-82A_-_TankBiathlon14part1-33.jpg",
        specs: { speed: "80 km/h", armament: "30mm 2A72", range: "600 km" },
        inService: 2013,
        users: ["Russia", "Kazakhstan", "Belarus"],
        status: "Active",
        fact: "The BTR-82A features an upgraded 30mm autocannon and advanced fire control system, making it significantly more lethal than previous BTR variants."
    },
    {
        id: 51,
        name: "BMP-3",
        type: "Infantry Fighting Vehicle",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/BMP-3_in_Saint_Petersburg.jpg/640px-BMP-3_in_Saint_Petersburg.jpg",
        specs: { speed: "70 km/h", armament: "100mm gun", range: "600 km" },
        inService: 1987,
        users: ["Russia", "UAE", "Kuwait", "South Korea"],
        status: "Active",
        fact: "The BMP-3 is unique among IFVs with its 100mm gun that can fire both conventional rounds and anti-tank guided missiles."
    },
    {
        id: 52,
        name: "BTR-90",
        type: "Armoured Personnel Carrier",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/BTR-90.jpg/640px-BTR-90.jpg",
        specs: { speed: "100 km/h", armament: "30mm 2A42", range: "800 km" },
        inService: 2004,
        users: ["Russia"],
        status: "Limited Service",
        fact: "Despite being one of the most advanced Russian APCs, the BTR-90 was produced in limited numbers due to high costs."
    },

    // Iranian APCs
    {
        id: 53,
        name: "Rakhsh",
        type: "Armoured Personnel Carrier",
        origin: "Iran",
        coords: [32.4279, 53.6880],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rakhsh_APC.jpg/640px-Rakhsh_APC.jpg",
        specs: { speed: "105 km/h", armament: "12.7mm MG", range: "700 km" },
        inService: 2011,
        users: ["Iran"],
        status: "Active",
        fact: "Named after the mythical horse of Persian hero Rostam, the Rakhsh is Iran's first domestically produced wheeled APC."
    },
    {
        id: 54,
        name: "Boragh",
        type: "Armoured Personnel Carrier",
        origin: "Iran",
        coords: [32.4279, 53.6880],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Boragh.jpg/640px-Boragh.jpg",
        specs: { speed: "65 km/h", armament: "12.7mm MG", range: "500 km" },
        inService: 2000,
        users: ["Iran"],
        status: "Active",
        fact: "The Boragh is based on the Soviet BMP-1 design but features significant Iranian modifications including improved armor and NBC protection."
    },

    // === ARMOURED BRIDGING SYSTEMS ===
    // Chinese Bridging
    {
        id: 55,
        name: "Type 84 AVLB",
        type: "Armoured Vehicle Launched Bridge",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Type_84_armored_vehicle-launched_bridge.jpg/640px-Type_84_armored_vehicle-launched_bridge.jpg",
        specs: { speed: "50 km/h", armament: "None", range: "450 km" },
        inService: 1984,
        users: ["China"],
        status: "Active",
        fact: "The Type 84 can deploy a 18-meter bridge capable of supporting 50-ton vehicles in just 3-5 minutes."
    },
    {
        id: 56,
        name: "Type 05 Amphibious Bridge",
        type: "Amphibious Bridging System",
        origin: "China",
        coords: [35.8617, 104.1954],
        image: "https://placehold.co/640x400/1a1a1a/00ff88?text=Type+05+Bridge",
        specs: { speed: "54 km/h", armament: "None", range: "500 km" },
        inService: 2005,
        users: ["China"],
        status: "Active",
        fact: "The Type 05 can create floating bridges across rivers up to 600 meters wide, supporting the rapid crossing of armored divisions."
    },

    // Russian Bridging
    {
        id: 57,
        name: "MTU-72",
        type: "Armoured Vehicle Launched Bridge",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/MTU-72_bridge_layer_-_TankBiathlon14part1-60.jpg/640px-MTU-72_bridge_layer_-_TankBiathlon14part1-60.jpg",
        specs: { speed: "60 km/h", armament: "None", range: "450 km" },
        inService: 1974,
        users: ["Russia", "Ukraine", "Syria", "Poland"],
        status: "Active",
        fact: "Based on the T-72 tank chassis, the MTU-72 can lay a 20-meter bridge in approximately 3 minutes under combat conditions."
    },
    {
        id: 58,
        name: "TMM-3M",
        type: "Truck-Mounted Bridge",
        origin: "Russia",
        coords: [61.5240, 105.3188],
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/TMM-3_truck-mounted_bridge.jpg/640px-TMM-3_truck-mounted_bridge.jpg",
        specs: { speed: "60 km/h", armament: "None", range: "1000 km" },
        inService: 1983,
        users: ["Russia", "Finland", "Czech Republic"],
        status: "Active",
        fact: "The TMM-3M can create bridges up to 40 meters long by connecting multiple units, capable of supporting 60-ton main battle tanks."
    },

    // Iranian Bridging
    {
        id: 59,
        name: "Zolfaqar Bridge Layer",
        type: "Armoured Vehicle Launched Bridge",
        origin: "Iran",
        coords: [32.4279, 53.6880],
        image: "https://placehold.co/640x400/1a1a1a/00ff88?text=Zolfaqar+Bridge",
        specs: { speed: "55 km/h", armament: "None", range: "400 km" },
        inService: 2016,
        users: ["Iran"],
        status: "Active",
        fact: "Named after Imam Ali's legendary sword, this Iranian-made bridge layer is based on the Zolfaqar tank chassis and can deploy bridges for heavy armor."
    }
];
